Auth
Aldekenzo/Flutter_test_1 pull request #1
Opened 2021-07-22 17:59 UTC by Aldekenzo

2021-07-23 05:26 UTC, aalystama requested changes

2021-07-23 05:26 UTC, aalystama commented on lib/main.dart
>  import 'package:flutter/material.dart';
Если ты используешь Cupertino, то нет смысла импортировать Material.

2021-07-23 05:26 UTC, aalystama commented on lib/src/screens/auth/auth_screen.dart
> +      backgroundColor: Color(0xFFF3F4F6),
Лучше выносить цвета в отдельную папку констант.

2021-07-23 05:26 UTC, aalystama commented on lib/src/screens/auth/auth_screen.dart
> +  */
На будущее, не стоит оставлять комментарии такого вида в своем коде.

2021-07-23 05:26 UTC, aalystama commented on lib/src/screens/auth/auth_screen.dart
> +  */
Если тебе надо оставить подобный комментарий, то сверху объясняй что он означает, иначе твои коллеги подумают что ты мусоришь в коде.

2021-07-24 11:12 UTC, maripbekoff commented on lib/constants/app_colors.dart
> +final Color backgroung = Color(0xFFF3F4F6);
Чтобы создать константу, необходимо использовать ключевое слово `const`. 
Посмотрите на пример из курса.

2021-07-24 11:12 UTC, maripbekoff commented on lib/src/screens/auth/auth_screen.dart
> +      backgroundColor: AppColors.backgroung,
Опечатка в названии константы

2021-07-24 11:53 UTC, Aldekenzo commented on lib/constants/app_colors.dart
> +final Color backgroung = Color(0xFFF3F4F6);
я до этого момента еще не дошел, поэтому сделал пока что так(в ютюбе видел что так делали)

2021-07-24 11:54 UTC, Aldekenzo commented on lib/src/screens/auth/auth_screen.dart
> +      backgroundColor: AppColors.backgroung,
ок исправлю)

2021-07-24 18:18 UTC, merged